on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    name: 'Check'
    steps:
      - uses: actions/checkout@v3
      - id: issue
        uses: blake-r/gha-jira-issue-get@initial
        with:
          jira_url: ${{ secrets.TEST_JIRA_URL }}
          jira_pat: ${{ secrets.TEST_JIRA_PAT }}
          issue_key: gbl-1
      - shell: bash
        run: test "$(jq -r '.fields.status.name' '${{ steps.issue.filename }}')" = "Done"
